### ISSUE TITLE
FeatureRequest: Add setup instructions

### ISSUE THREAD

**Issue by USSX-Hares** [dredknight/HoMM55-manual#1]
Currently, it is almost not possible to launch this app locally

**Comment by dredknight** [comment]
Hi @USSX-Hares what do you mean by locally ? You mean to get the repo from github and launch it ?

**Comment by USSX-Hares** [comment]
@dredknight, yes, exactly that
(I.e., from Linux)

**Comment by dredknight** [comment]
@USSX-Hares there is not much of a walkthrough

1. Download and install it the proper Linux distribution from [here](https://walkabout.mvmanila.com/downloads/)
2. Open Shoes cobler and install **Zip 2.0.2** gem as it is required to extract the manual text.
![image](https://user-images.githubusercontent.com/12410314/70260905-f9680380-1799-11ea-8838-d578c3a00180.png)
3. Clone the repo on your pc
4. Launch main.rb using the framework

Let me know how it goes.
